### ISSUE TITLE
Bestellung aufgeben

### ISSUE THREAD

**Issue by lottallegra** [heliogabal/inkshop_profile#12]
1. Im Warenkorb erscheint „Zahlungen richten an:“ – keine Möglichkeit etwas hinzuschreiben/auszuwählen:
 
![zahlungen richten an](https://cloud.githubusercontent.com/assets/23314904/20673668/4f920432-b586-11e6-97ae-d736fbd9c980.PNG)

2. Gibt es nur die Möglichkeit per Rechnung zu zahlen?

**Comment by heliogabal** [comment]
1. Haben wir schon besprochen, dass das Zahlung richten an: weg kann, da es an dieser Stelle keinen Sinn macht. Ist jetzt entfernt.

2. Momentan gibt es nur Auf Rechnung, möglicherweise später mehr.

**Comment by heliogabal** [comment]
Zahlung richten an ist jetzt entfernt.
