### ISSUE TITLE
Bestellformular "das Feld ... ist erforderlich"

### ISSUE THREAD

**Issue by lottallegra** [heliogabal/inkshop_profile#13]
Beim Ausfüllen des Kontaktformulars ist beim Durchklicken in verschiedenen Feldern „_Das Feld … ist erforderlich“_ eingeblendet worden, ohne dass ich auf „weiter“ geklickt hatte. Es wäre schöner, wenn diese Benachrichtigung erst dann erscheint, wenn man auf „weiter“ klickt um zum nächsten Schritt zu kommen, jedoch noch nicht alles ausgefüllt hat. Nicht aber, wenn man eh noch auf der Seite bleibt.

![info erforderlich](https://cloud.githubusercontent.com/assets/23314904/20673753/a03ff56a-b586-11e6-9be8-c55b97d76ee3.PNG)

**Comment by heliogabal** [comment]
Es entspricht der "best practice", die Fehlermeldungen direkt zu zeigen, wenn der Fehler passiert und nicht erst, wenn man das Formular abschickt: https://designmodo.com/ux-form-validation/ 

Dein Beispiel ist dann wohl eher der Testfall, der so wahrscheinlich nicht eintritt, weil man den Fehler auch gleich korrigiert und die Fehlermeldung dann wieder verschwindet, man also nie alle Fehlermeldungen auf einmal sieht.
