### ISSUE TITLE
"Rechnungsadresse stimmt mit Lieferadresse überein"

### ISSUE THREAD

**Issue by lottallegra** [heliogabal/inkshop_profile#14]
Es scheint die Möglichkeit zu fehlen einen Button anzuklicken _„Rechnungsadresse stimmt mit Lieferadresse überein"_. Unter Umständen, muss man dann die Felder zweimal ausfüllen, was vielleicht ein wenig mühselig ist…

**Comment by heliogabal** [comment]
Gibt es das bei dir nicht?
![screenshot-webshop dev inkota de 2016-11-28 18-05-00](https://cloud.githubusercontent.com/assets/389844/20677986/5a67a326-b595-11e6-8e2d-0ae9191ba120.png)

**Comment by lottallegra** [comment]
doch, jetzt schon. Gestern wurde das aus irgendeinem Grund nicht angezeigt.
