### ISSUE TITLE
Versandkostenangabe im Warenkorb

### ISSUE THREAD

**Issue by lottallegra** [heliogabal/inkshop_profile#15]
Wieso können die Versandkosten nicht schon in diesem Schritt angezeigt werden? Man hat keine Vorstellung davon, wie hoch die Versandkosten sein werden und es ist vielleicht etwas frustrierend, dass man erstmal alles ausfüllen muss, bevor man erfährt, wie viel man insgesamt bezahlen muss, denn ich nehme an, dass die Gesamtkosten evtl. die Kaufentscheidung beeinflussen:

![versandkosten4](https://cloud.githubusercontent.com/assets/23314904/20673926/39642c5c-b587-11e6-9b31-08dfa9b723ec.PNG)

**Comment by heliogabal** [comment]
das geht nicht, weil die Versandkosten sich aus der Lieferadresse berechnen, die im Warenkorb noch nicht eingegeben wurde. Allerdings gibt es an jedem Produkt einen Link zur Versandkostentabelle, auch im Warenkorb - der war allerdings kaputt, funktioniert allerdings jetzt wieder.
