### ISSUE TITLE
Überprüfung der Produktgewichte zur Berechnung der Versandkosten

### ISSUE THREAD

**Issue by lottallegra** [heliogabal/inkshop_profile#16]
Die Versandkosten scheinen noch nicht korrekt berechnet zu werden. Es kann ja nicht sein, dass ich für 58 Exemplare des Jahresberichts nur 2€ Versandkosten zahle…

![versandkostenpauschale](https://cloud.githubusercontent.com/assets/23314904/20674019/925f70dc-b587-11e6-8f80-274cd3e7d234.PNG)

**Comment by heliogabal** [comment]
Die Berechnung stimmt wahrscheinlich schon (bzw. kann erst dann sinnvoll getestet werden, wenn wir die Gewichte überprüft haben), aber das Gewicht war um zwei Stellen verschoben, d.h. 0.00133 Gramm statt 133 Gramm. 

Damit die Berechnung funktioniert, müssen natürlich zunächst alle Gewichte stimmen. Wenn das kontrolliert und korrigiert ist, muss man die Berechnung nochmal anschauen. Hier könnt ihr die Gewichte einfach überprüfen und ändern:

http://webshop.dev.inkota.de/admin/commerce/products/variations

**Comment by lottallegra** [comment]
Alles klar, danke. Ich glaube da muss man wahrscheinlich alle Produkte vorsichtshalber nochmal überprüfen, denn das Problem ist mir bei einigen Produkten aufgefallen.

**Comment by heliogabal** [comment]
müsste jetzt stimmen. Ich bin nochmal drüber gegangen und habe keine auffälligen Werte mehr bemerkt.
