### ISSUE TITLE
"Zurück zum Webshop"

### ISSUE THREAD

**Issue by lottallegra** [heliogabal/inkshop_profile#17]
Wenn ich alle Produkte aus dem Warenkorb leere, dann erscheint folgende Seite: 

![warenkorb leer](https://cloud.githubusercontent.com/assets/23314904/20674069/beb7920e-b587-11e6-8e08-074ae6822b4d.PNG)

Mir fehlt ein Button „zurück zum Webshop“ – hier gibt es nur die Möglichkeit direkt auf die Inkota-Website zu gelangen, nicht aber auf die Startseite des Webshops.

**Comment by heliogabal** [comment]
Nun, du kannst auf das Webshop-Logo klicken, um zurück zur Shopstartseite zu gelangen, oder eine der Suchfunktionen links benutzen. Zurück zum Webshop fände ich dagegen verwirrend, da du ja schon im Webshop bist.

**Comment by lottallegra** [comment]
Ich finde es eigentlich ganz gut wie es gelöst ist wenn man seine Bestellung abgeschlossen hat, denn es ist nicht wirklich selbsterklärend das die Graphik links oben auf die Startseite führt: 
![bestellung abgeschlossen](https://cloud.githubusercontent.com/assets/23314904/20711485/33577922-b640-11e6-9db2-d5513460c829.PNG)

**Comment by heliogabal** [comment]
Ok, hab jetzt einen Link hinzugefügt, wenn der Warenkorb leer ist.
