### ISSUE TITLE
Bestellbestätigung (E-Mail)

### ISSUE THREAD

**Issue by lottallegra** [heliogabal/inkshop_profile#18]
1. „Hallo [message:user:field-user-anrede]“ muss irgendwie ausgeblendet werden. Ich habe bei der Bestellung meine Anrede angegeben, trotzdem scheint ein Fehler bei der Generierung des Anschreibens vorzuliegen. 

2. Was bedeutet „ihre Bestelung Nr.  29"? Ist das Meine Bestellnummer? Dann würde ich schreiben „Ihre Bestellnummer lautet…“. Ansonsten hört es sich so an als hätte ich schon 29. Mal bei Inkota bestellt, aber das wäre ja auch eine Info, die für die Mail nicht relevant wäre.

![versandbestatigung](https://cloud.githubusercontent.com/assets/23314904/20674111/f3e30eb8-b587-11e6-9732-30b42688de39.PNG)

**Comment by heliogabal** [comment]
1. Kannst du das nochmal testen, ob jetzt das korrekte Herr/Frau ausgegeben wird?

2. Ja, das ist die Bestellnummer. Wir hatten schon besprochen, das die Texte der ganzen Mails noch überarbeitet werden sollen und sind auch schon auf die Problematik gestoßen. Habe ich jetzt vorläufig angepasst um es eindeutiger zu machen.

**Comment by lottallegra** [comment]
Es wird anders, aber immer noch nicht korrekt angezeigt...

![bestatigungsemail](https://cloud.githubusercontent.com/assets/23314904/20711426/ec2dbeee-b63f-11e6-808b-0ffb878a0a64.PNG)

**Comment by heliogabal** [comment]
Ah, hab den Fehler gefunden. Da ich das Profil von Hand angelegt hatte, habe ich die Anrede nicht ausgefüllt, das geht aber nicht, wenn man sich selbst anmeldet (Pflichtfeld). Habe jetzt deine Anrede ausgefüllt, jetzt sollte es gehen.
