### ISSUE TITLE
Anzahl der Produkte auf Lager

### ISSUE THREAD

**Issue by lottallegra** [heliogabal/inkshop_profile#19]
Ich kann von jedem Produkt max. 58-60 Exemplare in den Warenkorb legen. Bei größeren Mengen wird die Bestellung nicht in den Warenkorb gelegt. Dann kommt die Benachrichtigung _„Wir haben ... leider nur noch 56 Mal vorrätig“._ Sollte, man also nicht eher größere Zahlen angeben, falls jemand eine größere Bestellung aufgeben möchte? 

Ansonsten vielleicht irgendwo ein Vermerk, dass wenn man Interesse an z.B. mehr als 50 Exemplaren hat, dann soll man mit versand@inkota.de in Kontakt treten.

**Comment by heliogabal** [comment]
Stimmt, das ist unglücklich. Wir haben keine Ahnung, wieviel von welchen Produkten tatsächlich vorhanden sind, daher war die Idee, das zunächst auf einen Wert von 70 zu setzen und eine Überprüfung pro Produkt zu erzwingen, wenn noch "50" vorhanden sind. 

Allerdings hatte Doro schon fröhlich angekündigt, eine Inventur machen zu wollen, das würde dann das Problem beheben, wenn wir echte Zahlen hätten.

**Comment by heliogabal** [comment]
Zeitweiliger workaround: Die Fehlermeldung wird ergänzt:

Wir haben Südlink 176 - Juni 2016 aktuell nur noch 66 Mal vorrätig. Bitte schreiben Sie uns eine E-Mail an versand@inkota.de, um Nachbestellmöglichkeiten zu erfahren.
