### ISSUE TITLE
Ähnliche Produkte

### ISSUE THREAD

**Issue by lottallegra** [heliogabal/inkshop_profile#21]
In der Produktansicht _bearbeiten_ gibt es die Möglichkeit, _ähnliche Produkte_ zu nennen. Ich habe jetzt beispielhaft beim letzten Südlink zwei weitere Publikationen angegeben. Wenn man aber auf die Produktseite im Webshop geht, werden diese Publikationen nirgens angezeigt. 

In der Bearbeitungsmaske:
![ahnliche produkte](https://cloud.githubusercontent.com/assets/23314904/20713256/d24189c2-b647-11e6-9e67-22ab198bc2ea.PNG)

Im Webshop:
![ahnliche artikel](https://cloud.githubusercontent.com/assets/23314904/20713260/d4e433e6-b647-11e6-8325-65fa57ff103c.PNG)

**Comment by heliogabal** [comment]
ja, wir hatten noch nicht endgültig entschieden ob das eine sinnvolle Funktion ist, die wir nutzen wollen, daher wird das noch nicht dargestellt. Kann ich aber einfach einblenden, es macht also Sinn, ähnliche Produkte auch einzutragen.

**Comment by heliogabal** [comment]
Ähnliche Produkte sind jetzt aktiviert.
