### ISSUE TITLE
Bessere Newsletter-Abo Übersicht

### ISSUE THREAD

**Issue by heliogabal** [heliogabal/inkshop_profile#26]
Lotta braucht folgende Verbesserungen, um effizienter mit den Newsletter-Abos arbeiten zu können: 
~~- E-Mail an Lotta direkt, und nicht nur an Doro.~~
~~-  Sortierbare Anmeldedatums-Spalte.~~
~~- Entfernen unnötiger Spalten.~~
- Auftrennung von Anrede, Vorname, Nachname in einzelne Felder.

~~- korrekte Export-Funktion.~~

**Comment by lottallegra** [comment]
Sieht super aus, dankeschön!

**Comment by heliogabal** [comment]
Habe das noch ein wenig verbessert, so dass die Exportfunktion jetzt auch nach Datum gefiltert werden kann. In der Hoffnung, dass die Auftrennung der Adresse in Anrede, Vorname und Nachname nicht so wichtig ist, schließe ich das Ticket vorerst.
